spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sales_calculator
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/base-changelog.xml
    default-schema: public

cxf:
  path: /api
  jaxrs:
    component-scan: true
    client:
      connection:
        timeout: 60000
      receive:
        timeout: 60000
  servlet:
    init:
      service-list-path: /info

jaxrs:
  swagger:
    enabled: true
    resource-package: ru.dream_store_kzn.salescalculator
    schemes: https, http

sales:
  report:
    tax: 6.0
    sheet-name: Отчет по продажам
    status-cell-number: 0
    sku-cell-number: 5
    quantity-cell-number: 8
    marketplace-fee-cell-number: 12
    price-cell-number: 13
    promo-cell-number: 14
    net-cost-cell-number: 15
