server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: localhost:9092

jaxrs:
  swagger:
    enabled: true
    resource-package: ru.dream_store_kzn.salescalculator
    schemes: https, http

sales:
  report:
    tax: 6.0
    sheet-name: Отчет по продажам
    status-cell-number: 0
    sku-cell-number: 5
    quantity-cell-number: 8
    marketplace-fee-cell-number: 12
    price-cell-number: 13
    promo-cell-number: 14
    net-cost-cell-number: 15

topic:
   sales-report-profit: sales-report-profit
